name: unitconverter
description: A pure Dart library for converting values between common units.
version: 2.0.0
repository: https://github.com/fellow7000/unitconverter

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  lints: ^6.1.0
  test: ^1.31.1
